### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by davids74** [yantonov/gaudio#1]
I downloaded the files into a folder, and dragged it into Chrome Extensions page but it says,
"Manifest is not valid JSON. Line: 7, column: 1, Unexpected token."

**Comment by yantonov** [comment]
Hello! I've updated the installation instructions here 
https://github.com/yantonov/gaudio?tab=readme-ov-file#how-to-install

**Comment by davids74** [comment]
It responds with the same error. The unexpected token on the line 7 is 
!DOCTYPE html
https://imgur.com/QvVKRg6

**Comment by davids74** [comment]
Also it is not possible to clone the repository because it asks to register for cloudspace. I downloaded files one by one.
https://imgur.com/Le565Yx

**Comment by yantonov** [comment]
What cloudspace? it's just regular git repository

**Comment by yantonov** [comment]
<img width="667" alt="Screenshot 2024-01-05 180028" src="https://github.com/yantonov/gaudio/assets/1390348/73a13c29-2817-415c-94b6-f8cff078982b">

**Comment by davids74** [comment]
Try and log in from different account and explore your page

Forks
[ 0 forks](https://github.com/yantonov/gaudio/forks)
[Report repository](https://github.com/contact/report-content?content_url=https%3A%2F%2Fgithub.com%2Fyantonov%2Fgaudio&report=yantonov+%28user%29)
[Releases](https://github.com/yantonov/gaudio/releases)
No releases published
[Packages](https://github.com/users/yantonov/packages?repo_name=gaudio)
No packages published
Languages

**Comment by davids74** [comment]
Thanks for the screenshot, I found it. It was in the other tab in the code menu. And extension loads now!

**Comment by yantonov** [comment]
I didn't publish this tiny extension, because now sure it's worth it for the store.
But to simplify downloading podcasts it's nice and it's possible to install manually (there are some edge cases with iframes, but for most cases, it works).

If it helps it would be great!
Have a nice weekend :)

**Comment by yantonov** [comment]
I suppose we can consider this question as resolved :)
